### ISSUE TITLE
convert error ahout the audio of 网易云播客

### ISSUE THREAD

**Issue by sleepy2con** [ww-rm/ncmdump-py#1]
D:\Code_space\ncmdump-py-1.0.1> python -m ncmdump --in-folder "D:\CloudMusic\VipSongsDownload\电台节目" --dump-metadata --dump-cover
[17:36:00] ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 03 踏遍万水千山.ncm ->        __main__.py:49
           Invalid base64-encoded string: number of data characters (1429) cannot be 1 more than a
           multiple of 4
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 04                            __main__.py:49
           康桥恋歌，原来爱情是苦涩的.ncm -> Invalid base64-encoded string: number of data characters
           (1493) cannot be 1 more than a multiple of 4
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 05 转身你还在，真好.ncm ->    __main__.py:49
           Invalid base64-encoded string: number of data characters (1365) cannot be 1 more than a
           multiple of 4
[17:36:01] ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 06 泰戈尔来了.ncm -> Invalid  __main__.py:49
           base64-encoded string: number of data characters (1429) cannot be 1 more than a multiple of 4
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 07 没有归宿的爱，就断了吧.ncm __main__.py:49
           -> Incorrect padding
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 08 李夫人的离世.ncm ->        __main__.py:49
           Invalid base64-encoded string: number of data characters (1429) cannot be 1 more than a
           multiple of 4
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 09 亲手做嫁衣.ncm -> Invalid  __main__.py:49
           base64-encoded string: number of data characters (1429) cannot be 1 more than a multiple of 4
[17:36:02] ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 10 蜜月期的建筑之旅.ncm ->    __main__.py:49
           Incorrect padding
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 11 每一位诗人，都是天才.ncm   __main__.py:49
           -> Incorrect padding
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 12 疗养时的诗人时光.ncm ->    __main__.py:49
           Incorrect padding
[17:36:03] ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 13 太太的客厅.ncm -> Invalid  __main__.py:49
           base64-encoded string: number of data characters (1429) cannot be 1 more than a multiple of 4
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 14 轻轻地，他走了.ncm ->      __main__.py:49
           Incorrect padding
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 15                            __main__.py:49
           日记，这段情成了无人知晓的秘密.ncm -> Incorrect padding
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 16 我愿为你写尽哀思.ncm ->    __main__.py:49
           Incorrect padding
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 17 天涯海角去找塔.ncm ->      __main__.py:49
           Incorrect padding
[17:36:04] ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 18                            __main__.py:49
           体力不支，就把时间交给书.ncm -> Invalid base64-encoded string: number of data characters
           (1493) cannot be 1 more than a multiple of 4
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 19 没有苦难，做不出学问.ncm   __main__.py:49
           -> Invalid base64-encoded string: number of data characters (1365) cannot be 1 more than a
           multiple of 4
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 20 大小姐，也要经历磨难.ncm   __main__.py:49
           -> Incorrect padding
           ERROR: D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 21 一代才女林徽因.ncm ->      __main__.py:49
           Incorrect padding
  Dumping files ---------------------------------------- 100% 0:00:00 0:00:04

Encountered an issue when converting paid podcast files from Netease Cloud Music. I purchased and downloaded these audio files in ncm format, but the conversion is unsuccessful. Here are the error messages. Could you please take a look and help me understand what's going wrong?

**Comment by ww-rm** [comment]
@sleepy2con Could you please provide the ncm files you need to decrypt? I can't access the corresponding file on the app (need to pay).

If possible,  I hope you can provide file `D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 03 踏遍万水千山.ncm` and file `D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 07 没有归宿的爱，就断了吧.ncm`, they are two different types of errors.

You can send the files to my email ww-rm@qq.com by attachments or attach files in the comment, I'll debug them when I receive.

**Comment by ww-rm** [comment]
@sleepy2con  Could you please provide the ncm files you need to decrypt? I can't access the corresponding file on the app (need to pay).

If possible,  I hope you can provide file `D:\CloudMusic\VipSongsDownload\电台节目\北方文艺出版社 - 03 踏遍万水千山.ncm` or some other files for me.

You can send the files to my email ww-rm@qq.com by attachments or attach files in the comment, I'll debug them when I receive.

**Comment by ww-rm** [comment]
@sleepy2con Thanks for your issue, I have added support for dj file in the latest version, try decrypt them again.

**Comment by sleepy2con** [comment]
> @sleepy2con Thanks for your issue, I have added support for dj file in the latest version, try decrypt them again.
@ww-rm appreciate your swift response and the fix for the issue! I've just tried decrypting the dj files with the latest version, and it worked like a charm. Thanks a bunch for your support!
